language: java

sudo: false

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - cd practicals/code
  - mvn install -DskipTests=true -q
  - cd ../..

  - cd coursework1/csc3423-cw1
  - mvn install -DskipTests=true -q
  - mvn test
  - ./run ../TrainFold0 ../TestFold0

notifications:
  email:
    on_success: change
    on_failure: change
