language: java

sudo: false

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - cd practicals/code
  - mvn install -DskipTests=true -q
  - cd ../..

  - cd coursework-implementation
  - mvn install -DskipTests=true -q
  - mvn test
  - ./run src/test/resources/TrainFold0 src/test/resources/TestFold0

notifications:
  email:
    on_success: change
    on_failure: change
