language: java

sudo: false

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - cd practicals/code
  - mvn install -DskipTests=true -q
  - cd ../..
  - cd coursework-implementation
  - mvn install -DskipTests=true
  - mvn test

notifications:
  email:
    on_success: change
    on_failure: change
