language: java

sudo: false

jdk:
  - openjdk7
  - oraclejdk7

script:
  - cd coursework1/csc3423-cw1
  - mvn install -DskipTests=true -q
  - mvn test

notifications:
  email:
    on_success: change
    on_failure: change
